name: Debug Tag Fetch and Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched

      # Step 2: Fetch all tags
      - name: Fetch tags
        run: |
          git fetch --tags
          git tag  # List all tags to verify they are fetched

      # Step 3: Debug latest tag fetching
      - name: Debug latest tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "none")
          
          echo "DEBUG: Output of git describe --tags:"
          git describe --tags || echo "No tags found"

          if [ "$TAG" != "none" ]; then
            echo "Latest tag found: $TAG"
          else
            echo "No tags found. Defaulting to v0.0.0."
            TAG="v0.0.0"
          fi

          echo "latest_tag=$TAG" >> $GITHUB_ENV
