name: Automated Versioning with Tags Based on Commit Messages

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched

      # Step 2: Fetch all tags
      - name: Fetch tags
        run: git fetch --tags

      # Step 3: Get the latest tag or default to v0.0.0
      - name: Get latest tag
        id: tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $TAG"
          echo "latest_tag=$TAG" >> $GITHUB_ENV

      # Step 4: Determine version bump based on commit messages
      - name: Analyze commits for version bump
        id: bump
        run: |
          TAG=${{ env.latest_tag }}
          VERSION=${TAG#v}  # Remove 'v' prefix
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          COMMITS=$(git log --pretty=%B ${TAG}..HEAD)

          BUMP="patch"
          if echo "$COMMITS" | grep -q "BREAKING CHANGE"; then
            BUMP="major"
          elif echo "$COMMITS" | grep -q "^feat:"; then
            BUMP="minor"
          elif echo "$COMMITS" | grep -q "^fix:"; then
            BUMP="patch"
          fi

          if [ "$BUMP" = "major" ]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [ "$BUMP" = "minor" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif [ "$BUMP" = "patch" ]; then
            PATCH=$((PATCH + 1))
          fi

          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      # Step 5: Create and push the new tag
      - name: Create and push new tag
        run: |
          git tag ${{ env.new_version }}
          git push origin ${{ env.new_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Generate Release Notes
      - name: Generate Release Notes
        run: |
          COMMITS=$(git log --pretty=format:"* %s" ${TAG}..HEAD)
          echo "Release Notes:" > RELEASE_NOTES.md
          echo "$COMMITS" >> RELEASE_NOTES.md
          cat RELEASE_NOTES.md

      # Step 7: Commit and push the generated RELEASE_NOTES.md file
      - name: Configure Git identity
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit and push RELEASE_NOTES.md
        run: |
          git add RELEASE_NOTES.md
          git commit -m "chore: update release notes for ${{ env.new_version }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: Update the CHANGELOG.md file
      - name: Update CHANGELOG.md
        run: |
          COMMITS=$(git log --pretty=format:"* %s" ${TAG}..HEAD)
          echo "## ${{ env.new_version }} - $(date +'%Y-%m-%d')" >> CHANGELOG.md
          echo "$COMMITS" >> CHANGELOG.md
          cat CHANGELOG.md

      # Step 9: Commit and push the updated CHANGELOG.md file
      - name: Configure Git identity
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
      - name: Commit and push CHANGELOG.md
        run: |
          git add CHANGELOG.md
          git commit -m "chore: update changelog for ${{ env.new_version }}"
          git push origin main  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
